from os import getenv


SERVICE_NAME = 'shipping'
KAFKA_BOOTSTRAP_SERVERS = getenv('KAFKA_BOOTSTRAP_SERVERS')
PAYED_ORDERS_TOPIC = getenv('PAYED_ORDERS_TOPIC')
SENT_ORDERS_TOPIC = getenv('SENT_ORDERS_TOPIC')